- name: Instalador do VEAM AGENT FOR LINUX
  hosts: all
  become: yes
  tasks:
############ ADICIONAR REPOSITORIO DO VEAM #############
    - name: Adicionando repositorio do veam
      shell: sudo yum -y install https://repository.veeam.com/backup/linux/agent/rpm/el/8/x86_64/veeam-release-el8-1.0.7-1.x86_64.rpm
########### INSTALAR O VEAM AGENT ##############
    - name: Instalando o repositorio do veam
      shell: yum install -y --nogpgcheck veeam
###############################################
