---
- name: Executar o sript para execucao do playbook
  hosts: 192.168.56.4
  become: true
  tasks:
    - name: Executando script
      become_user: ansible
      shell: '/etc/ansible/playbooks/6-website_monitor/linuxServerMonitor.yml; /var/www/html/webmonitor/script/data-insert.sh'
...
