---
- name: Remediacao Automatica do Servidor com processo down
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 8000
  rules:
    - name: Serviço Tunned desligado
      condition: event.alert.labels.job == "tuned" and event.alert.status == "inactive"
      action:
        run_playbook:
          name: correção_processo.yml
    - name: debug
      condition: event.alert.labels.job == "tuned"
      action:
        debug:
