---
- name: Executar o sript para execucao do playbook
  hosts: 192.168.1.24
  vars:
    vagrant_file: /Users/felipegiffu/ansible-scripts
  tasks:
    - name: Preparando para provisionar a Maquina Virtual (VM)
      shell: 'cd /Users/felipegiffu/ansible-scripts'
    - name: Validando se possui o vagranfile ou será baixado um novo
      stat:
        path: '{{ vagrant_file }}'
      register: register_vagrant_file
    - name: Aguarde em quanto provisionamos a imagem da Maquina Virtual (VM)
      shell: '/usr/local/bin/vagrant init centos/7'
      when: register_vagrant_file == false
      ignore_errors: no
    - name: Aguarde em quanto provisionamos a imagem da Maquina Virtual (VM)
      shell: '/Users/felipegiffu/ansible-scripts/provisionamentovm.sh'
      register: process_httpd
      ignore_errors: yes
    - debug:
        msg: O PROVISIONAMENTO DA NOVA VM FOI REALIZADO COM SUCESSO
...
