---
- name: Start and Stop process
  hosts: all
  become: true
  tasks:
   - name: Start service nginx
     service:
       name: nginx
       state: started
       enabled: yes
     when: "'Start' in status_process"
   - name: Stop service nginx
     service:
       name: nginx
       state: stopped
       enabled: no
     when: "'Stop' in status_process"
   - name: Check status of process if system is RHEL
     shell: "systemctl status nginx"
     register: process
   - debug:
       var: process.stdout_lines 
     ignore_errors: yes
...
