---
- name: Start and Stop process
  hosts: all
  become: true
  tasks:
   - name: Start service nginx
     service:
       name: httpd
       state: started
       enabled: yes
     when: "'start' in status_process"
   - name: Stop service nginx
     service:
       name: httpd
       state: stopped
       enabled: no
     when: "'stop' in status_process"
   - name: Check status of process
     shell: "systemctl status nginx"
     when: ansible_distribution == 'RedHat'
   - name: Check status of process
     shell: "apt status nginx"
     when: ansible_distribution == 'Ubuntu'
...
