#############################################################################################
###   NAME:              Start Stop Process                                                  #
###   VERSION:           1.0                                                                 #
###   DESCRIPTION:       Start/Stop Process with interaction                                 #
###   WHY:               Ansible Lab                                                         #
###   CREATED BY:        Felipe Thomaz Giffu                                                 #
###   PLATFORM:          Linux.                                                              #
#############################################################################################
---
####################### START/STOP #######################
- name: Start and Stop process
  hosts: all
  become: true
  tasks:
   - name: Start no serviço tuned.service
     service:
       name: tuned.service
       state: started
       enabled: yes
     when: 
       - "'Start' in status_process"
       - "'tuned.service' in name_process"
   
   - name: Start no serviço httpd
     service:
       name: httpd
       state: started
       enabled: yes
     when: 
       - "'Start' in status_process" 
       - "'httpd' in name_process"
       - ansible_distribution == 'RedHat'
   
   - name: Stop no serviço tuned.service
     service:
       name: tuned.service
       state: stopped
       enabled: no
     when: 
       - "'Stop' in status_process"
       - "'tuned.service' in name_process"
   
   - name: Stop no serviço httpd
     service:
       name: httpd
       state: stopped
       enabled: no
     when: 
       - "'Stop' in status_process" 
       - "'httpd' in name_process"
       - ansible_distribution == 'RedHat'
####################### CHECK STATUS #######################        
   - name: Checkar o status do serviço tuned.service 
     shell: "systemctl status tuned.service"
     register: process_nginx
     ignore_errors: yes
     when: "'tuned.service' in name_process"
   - debug:
       var: process_nginx.stdout_lines 
     when: "'tuned.service' in name_process"
   
   - name: Checkar o status do serviço httpd
     shell: "systemctl status httpd"
     register: process_httpd
     ignore_errors: yes
     when: "'httpd' in name_process"
   - debug:
       var: process_httpd.stdout_lines 
     when: 
       - "'httpd' in name_process" 
       - ansible_distribution == 'RedHat'
   
   - debug:
       msg: Não há servico HTTPD no Ubuntu. Somente nos RHEL. No Ubutun é necessário instalar e configurar o servico Apache2
     when: 
       - "'httpd' in name_process"
       - ansible_distribution == 'Ubuntu'
...
