---
- name: Start and Stop process
  hosts: all
  become: true
  tasks:
   - name: Start service nginx
     service:
       name: nginx
       state: started
       enabled: yes
     when: "'Start' in status_process"
   - name: Stop service nginx
     service:
       name: nginx
       state: stopped
       enabled: no
     when: "'Stop' in status_process"
   - name: Check status of process
     shell: "systemctl status nginx"
     register: process
     when: ansible_distribution == 'RedHat'
   - name: Check status of process
     shell: "apt status nginx"
     register: process
     when: ansible_distribution == 'Ubuntu'
   - debug:
       var: process.stdout
...
