---
- name: Start and Stop process
  hosts: all
  become: true
  tasks:
   - name: Start service nginx
     service:
       name: nginx
       state: started
       enabled: yes
     when: 
       - "'Start' in status_process"
       - "'nginx' in name_process"
   - name: Start service httpd
     service:
       name: httpd
       state: started
       enabled: yes
     when: 
       - "'Start' in status_process" 
       - "'httpd' in name_process"
       - ansible_distribution == 'RedHat'
   - name: Stop service nginx
     service:
       name: nginx
       state: stopped
       enabled: no
     when: 
       - "'Stop' in status_process"
       - "'nginx' in name_process"
 #  - name: Check status of process if system is RHEL
 #    shell: "systemctl status nginx"
 #    register: process
 #    ignore_errors: yes
 #  - debug:
 #      var: process.stdout_lines 
...
