#############################################################################################
###   NAME:              Start Stop Process                                                  #
###   VERSION:           1.0                                                                 #
###   DESCRIPTION:       Start/Stop Process with interaction                                 #
###   WHY:               Ansible Lab                                                         #
###   CREATED BY:        Felipe Thomaz Giffu                                                 #
###   PLATFORM:          Linux.                                                              #
#############################################################################################
---
####################### START/STOP #######################
- name: Start and Stop process
  hosts: all
  become: true
  tasks:
   - name: Start service nginx
     service:
       name: nginx
       state: started
       enabled: yes
     when: 
       - "'Start' in status_process"
       - "'nginx' in name_process"
   
   - name: Start service httpd
     service:
       name: httpd
       state: started
       enabled: yes
     when: 
       - "'Start' in status_process" 
       - "'httpd' in name_process"
       - ansible_distribution == 'RedHat'
   
   - name: Stop service nginx
     service:
       name: nginx
       state: stopped
       enabled: no
     when: 
       - "'Stop' in status_process"
       - "'nginx' in name_process"
   
   - name: Stop service httpd
     service:
       name: httpd
       state: stopped
       enabled: no
     when: 
       - "'Stop' in status_process" 
       - "'httpd' in name_process"
       - ansible_distribution == 'RedHat'
####################### CHECK STATUS #######################        
   - name: Check status of NGINX process 
     shell: "systemctl status nginx"
     register: process_nginx
     ignore_errors: yes
     when: "'nginx' in name_process"
   - debug:
       var: process_nginx.stdout_lines 
     when: "'nginx' in name_process"
   
   - name: Check status of HTTPD process
     shell: "systemctl status httpd"
     register: process_httpd
     ignore_errors: yes
     when: "'httpd' in name_process"
   - debug:
       var: process_httpd.stdout_lines 
     when: "'nginx' in name_process" 

   
   - debug:
       msg: Não há HTTPD no Ubuntu. Somente nos RHEL.
     when: "'httpd' in name_process"
...
